name: Build deb

on:
  push:
    paths:
      - 'control' 
    branches:
      - 'main'  # 仅在推送到 main 分支时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Clear build cache
        run: |
          rm -rf .theos
          rm -rf packages
          rm -rf obj
          find . -name "*.o" -delete
          find . -name "*.dylib" -delete
          
      - name: Bump package version
        run: |
          VERSION_PREFIX="1.0.0"
          VERSION_BASE=23
          VERSION="${VERSION_PREFIX}-$((VERSION_BASE + ${{ github.run_number }}))"

          echo "Using version: $VERSION"
          sed -i '' "s/^Version: .*/Version: ${VERSION}/" control
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Prepare Theos
        uses: axs66/theos-action@main

      - name: Build package
        run: |
          rm -f ${{ github.workspace }}/packages/*.deb
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: List generated Deb packages
        run: ls ${{ github.workspace }}/packages

      - name: 创建 Release
        if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        with:
          token: ${{ secrets.PAT }}
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: WeChatIslandBanner v${{ env.PACKAGE_VERSION }}
          files: ${{ github.workspace }}/packages/*.deb

      - name: Upload specific Deb packages
        uses: actions/upload-artifact@v4.3.3
        with:
          name: WeChatIslandBanner v${{ env.PACKAGE_VERSION }}
          path: ${{ github.workspace }}/packages/*.deb
